export type Language = 'zh' | 'en' | 'ja' | 'ko' | 'fr' | 'es' | 'de';

export type Theme = 'dark' | 'light';

export type GroupingMode = 'none' | 'year' | 'month' | 'day';

export type MorningStarPersona = string;

/**
 * Phase 4 Week 2 (§5.1.A) — user-created starlight (custom persona).
 *
 * Each `CustomPersona` is a 「自定义启明星」 entry generated by the
 * Persona Builder dialog wizard. The system prompt is synthesised by
 * `/api/persona-build` from the user's 5-7-step descriptive answers
 * (no LLM-fine-tuning, no third-party data upload). Stored encrypted
 * in IDB, never sent to any server beyond the same-process AI proxy.
 *
 * Naming: `name` is the visible label that joins the user's
 * guiding-star directory (consumed by `useGuidingStarsEditor` /
 * Morning Star). `systemPrompt` is the AI-generated persona body
 * (~1500 chars typical). `kind` distinguishes regular custom personas
 * from the future `memoir` variant (Week 3-5) so the UI can branch
 * between the lighter "工具型" wizard and the deeper Memoir flow.
 */
export type CustomPersonaKind = 'persona' | 'memoir';

/**
 * Phase 4 Week 3 (§5.1.B) — long-term memory point for **心象 (Memoir)**.
 *
 * Each `Memory` is a single fact / emotion / relationship anchor / life
 * milestone extracted by the LLM after a Memoir conversation closes.
 * The memory store grows over time; on the next Memoir session, the
 * top-N most relevant memories are retrieved and injected into the
 * system prompt so the 心象 "remembers" past conversations.
 *
 * Privacy posture (CRITICAL):
 *   - Stored encrypted in IDB, never sent to any server beyond the
 *     same-process AI proxy at retrieval time.
 *   - The user has FULL control via `MemoryManagementPanel`: view,
 *     edit, delete any single memory, or wipe the entire bank for
 *     a Memoir.
 *   - The extractor's prompt template explicitly forbids embedding
 *     third-party PII (phone numbers / addresses / emails) into the
 *     memory body.
 *
 * `category`:
 *   - `'fact'`     — concrete events, plans, occurrences ("用户周五要面试")
 *   - `'emotion'`  — emotional state markers ("用户最近很焦虑")
 *   - `'relationship'` — third-party relationship state ("用户与同事 X 关系紧张")
 *   - `'milestone'` — date-anchored life events ("今天是用户爷爷忌日")
 *
 * `memoirId`:
 *   - Memories are scoped per-心象 (per-Memoir-persona). A user with
 *     multiple Memoirs (心中的爷爷, 大学导师, 22岁的自己) keeps
 *     completely separate memory banks for each — no cross-pollination.
 */
export type MemoryCategory = 'fact' | 'emotion' | 'relationship' | 'milestone';

export interface Memory {
  /** Unique id (`memory-<base32>`). Stable across edits. */
  id: string;
  /** Owning Memoir persona id (`memoir-<base32>`). Indexes into
   *  `CustomPersona[]` where `kind === 'memoir'`. */
  memoirId: string;
  /** Memory taxonomy bucket (see jsdoc above). */
  category: MemoryCategory;
  /** The memory body itself, ≤ 240 chars. Short on purpose: this is
   *  a recall hook, not a transcript. */
  body: string;
  /** UTC ms when the memory was extracted. */
  createdAt: number;
  /** UTC ms of the last edit. Equals `createdAt` if never touched. */
  updatedAt: number;
  /** Optional source-conversation reference (for "where did I learn
   *  this?" UX). Implementation-defined string; v1 uses a timestamp
   *  hash. */
  sourceRef?: string;
  /**
   * Phase 4 Week 4 (§2.5 of [`docs/memoir-memory-system.md`](
   * ../docs/memoir-memory-system.md)) — soft-delete timestamp.
   *
   * When set, the memory is **excluded** from `selectMemoriesForRecall`
   * AND from the per-Memoir capacity count, but still resides in IDB.
   * The `useMemoryStore` mount sweep hard-deletes anything whose
   * `deletedAt < now - 30d`. Until then the user can restore via
   * Settings → 心象管理 → Recycle bin.
   *
   * Backwards-compat: existing v3 backups + pre-W4 records have
   * `deletedAt === undefined` which reads as "not deleted" — no
   * migration needed.
   */
  deletedAt?: number;
  /**
   * Phase 4 Week 4 (§2.2) — soft pointer to a sibling memory the
   * dedup ranker considered "near-similar but not collapsable".
   * Reserved for a future merge-UI; written but not yet read.
   * Optional, no migration needed.
   */
  relatedTo?: string;
}

/**
 * Phase 4.5 §A (Letter Mode) — `PendingLetter` is the user's
 * in-flight letter to a Memoir. Stored encrypted-at-rest in
 * IndexedDB; on every Dashboard mount a sweep checks whether any
 * letter is due (`now >= deliverAt`) and dispatches it to the
 * Morning Star pipeline. The reply lands as a special
 * `DiaryEntry` with `isLetterReply: true`.
 *
 * Why `PendingLetter` is a separate domain object (not just a
 * draft entry):
 *   - The whole point of letter mode is the *delay* and the
 *     ritual. A draft entry would surface in the entries grid
 *     immediately; a pending letter intentionally hides until
 *     it is delivered.
 *   - The reply path is a Memoir AI call, not a user write — the
 *     persistence shape mirrors that lifecycle (status field +
 *     dispatchedAt + replyEntryId).
 *
 * `status` lifecycle:
 *   - `'pending'`  → `'delivered'` (sweep picked it up, AI call
 *                                    succeeded, reply entry exists)
 *   - `'pending'`  → `'cancelled'` (user cancelled before deliverAt)
 *   - `'pending'`  → `'failed'`    (AI call repeatedly failed; the
 *                                    sweep gives up after 3 attempts)
 *
 * Privacy posture: same as memories — local-only IDB, never
 * mirrored to a server. The user can preview / cancel pending
 * letters in Settings → 心象管理 → "信件".
 */
export type LetterStatus = 'pending' | 'delivered' | 'cancelled' | 'failed';

export interface PendingLetter {
  /** Unique id (`letter-<base32>`). */
  id: string;
  /** Owning Memoir persona id (`memoir-<base32>`). */
  memoirId: string;
  /** Plain-text body of the user's letter. ≤ 4000 chars. */
  body: string;
  /** UTC ms when the user composed the letter. */
  composedAt: number;
  /** UTC ms when the sweep should attempt delivery. */
  deliverAt: number;
  /** Lifecycle state — see jsdoc above. */
  status: LetterStatus;
  /** UTC ms of the last delivery attempt (used to compute back-off
   *  for failed letters). Undefined until first attempt. */
  lastAttemptAt?: number;
  /** Number of failed delivery attempts. The sweep gives up after
   *  3 and flips status to `'failed'`. */
  attempts?: number;
  /** When `status === 'delivered'`, the `DiaryEntry.id` of the
   *  reply that was minted. Lets the Settings letters view jump
   *  the user straight to the reply. */
  replyEntryId?: string;
}

export interface CustomPersona {
  /** Unique id (`persona-<base32>` for personas, `memoir-<base32>` for
   *  memoirs). Stable across rename / edit. */
  id: string;
  /** Visible display name in the guiding-star list (e.g. "乔布斯"). */
  name: string;
  /** Short user-facing description (e.g. "Apple 创始人 / 极客哲学家"). */
  description?: string;
  /** Persona type — distinguishes the lightweight Persona Builder
   *  flow (Week 2) from the upcoming Memoir flow (Week 3-5). */
  kind: CustomPersonaKind;
  /** AI-synthesised system prompt fed to Morning Star at chat time.
   *  Editable by the user via PersonaPreview. */
  systemPrompt: string;
  /** ISO-like UTC ms when the persona was created. */
  createdAt: number;
  /** UTC ms of the last edit (name / description / systemPrompt). */
  updatedAt: number;
  /** Optional structured snapshot of the wizard answers used to
   *  generate the persona. Kept so the user can re-open the wizard
   *  pre-filled and tweak. Never includes third-party PII. */
  builderAnswers?: Record<string, string>;
}

export interface Principle {
  id: string;
  text: string;
  year: number;
  date?: string; // New: Optional full date for entry-derived principles
  createdAt: number;
  showOnHome: boolean; // New: Whether to display on the landing page
  containerId?: string; // New: Link to a storage container
}

export interface Container {
  id: string;
  name: string;
  description?: string;
  color?: string;
  icon?: string;
  createdAt: number;
}

export interface Attachment {
  type: 'image' | 'video' | 'audio' | 'pdf' | 'other';
  data: string; // Base64 or Blob URL (Base64 for persistence)
  name: string;
  mimeType: string;
}

export interface DiaryEntry {
  id: string;
  title: string;
  content: string;
  createdAt: number;
  updatedAt?: number; // New: Last modified timestamp for sync resolution
  tags: string[];
  isLocked: boolean;
  isEncrypted?: boolean; // New: Whether the content is encrypted with a master password
  isArchived?: boolean; // New field for Bio-Vault
  migrated?: boolean; // Added for space separation
  archivedToShip?: boolean; // Added for space separation
  unlockAt?: number; // New: Time when the entry becomes accessible
  morningStarAnalysis?: string; // Persisted Morning Star result
  morningStarPersona?: MorningStarPersona; // Deprecated: single persona
  morningStarPersonas?: string[]; // New: multiple personas
  reflection?: string; // New: User reflection on the entry
  attachment?: Attachment; // New: Media attachment
  containerId?: string; // New: The storage package this entry belongs to
  /**
   * Phase 4 §4.a-1 — sample reflection seeded by `services/sampleEntries.ts`
   * after onboarding completes. Sample entries:
   *   - render with a special "示例" badge in `EntryGrid` / `ArchiveEntryCard`
   *   - are auto-removed by `useDiaryData.addEntry` once the user writes
   *     their first real entry (lifecycle option C from the §4.a-1 brief)
   *   - serve only as activation hooks; they never count toward stats /
   *     filters / backups in a way that pollutes user data
   * Optional + additive so older backups (missing the field) round-trip
   * cleanly through `dashboardImport.ts` and `sanitizeEntry`.
   */
  isSample?: boolean;
  /**
   * Phase 4.5 §A (Letter Mode) — `true` when this entry was minted
   * by the letter-delivery sweep as a Memoir's reply to the user's
   * letter. EntryGrid renders a soft amber 「信」envelope badge for
   * these entries; Viewer plumbs the original letter id into the
   * "你这封信" affordance.
   *
   * Optional ⇒ legacy entries + non-letter Morning Star analyses
   * read as `undefined` (treated as "regular entry"). No backup
   * schema bump required.
   */
  isLetterReply?: boolean;
  /** Phase 4.5 §A — back-reference to the `PendingLetter.id` that
   *  produced this reply. Used by the Settings letters view to
   *  link "delivered letter → reply entry". */
  letterId?: string;
  /**
   * Phase 4.5 §B (Echo Chamber) — `true` when this entry was
   * minted from a multi-persona round-table session. EntryGrid
   * renders a soft cyan 「圆桌」 badge for these entries; Viewer
   * shows the original prompt in a special preface block.
   *
   * Optional ⇒ existing entries read as `undefined` (regular).
   * No backup-schema bump required (additive field).
   */
  isEchoChamber?: boolean;
  /** Phase 4.5 §B — the user's original "round-table question"
   *  that produced this entry. Stored alongside the analysis so
   *  the Viewer can render it as the preface even after re-edits
   *  to the entry's `content`/`reflection` fields. */
  echoChamberQuery?: string;
}

export enum AppState {
  COVER = 'COVER', // New Landing Page (Includes Fragments)
  ONBOARDING = 'ONBOARDING', // Initial Setup
  DASHBOARD = 'DASHBOARD',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
  ARCHIVE = 'ARCHIVE', // Bio-Vault
}
