/**
 * Phase 5 §5.1 — `lib/licenseKeyring.ts`
 *
 * Single source of truth for the **master public keys** the client
 * trusts when verifying license tokens. The corresponding **private
 * keys** never enter this codebase — they live on a VECTOR-team
 * minter server that only runs server-side.
 *
 * # Keys we ship
 *
 * - **`dev-2026`** — a deterministic public key derived from a
 *   well-known seed (`'vector-dev-license-seed-2026'`). The
 *   matching private key is reproducible by
 *   `scripts/dev-mint-license.mjs`, so any developer can mint a
 *   working token locally without touching a server. This kid is
 *   accepted in EVERY build (including production) for now —
 *   we'll narrow that in Phase 5.2 once the production minter
 *   ships, by gating it on `import.meta.env.MODE !== 'production'`.
 *
 * - **`vector-master-2026`** — the production public key. Stays
 *   `null` in this commit (we don't have a real minter yet);
 *   Phase 5.2 will replace `null` with the real 32-byte public
 *   key once the production keypair is generated and the private
 *   key is sealed in the minter's secret store.
 *
 * # Why a separate file
 *
 * - `services/licenseToken.ts` stays pure-logic and easy to test.
 * - The keyring is what changes during key rotation — keeping it
 *   small and isolated keeps the diff focused.
 * - Tests can build their own keyring via `signLicenseToken` and
 *   pass it explicitly to `verifyLicenseToken`, so the production
 *   keyring is only consulted by real client code paths.
 */

const DEV_KID = 'dev-2026' as const;

/** Seed string the dev minter uses to derive its keypair. The
 *  seed is intentionally NOT a secret (it's checked into source);
 *  the protection model is "anyone can mint a dev token, but the
 *  resulting token is `kid: 'dev-2026'` which a future production
 *  build can refuse". */
export const DEV_LICENSE_SEED = 'vector-dev-license-seed-2026';

/** SHA-256 derives a 32-byte secret key from the seed string. We
 *  use a sync helper here instead of WebCrypto so this module
 *  stays usable from both client and the dev-minter Node script
 *  without async setup. */
const deriveDevSecretKey = (): Uint8Array => {
  // We can't import @noble/hashes at module-init in the browser
  // bundle (it doesn't gracefully degrade if Web Crypto is
  // missing). Instead, we hand-spin a small "shake the seed
  // through a deterministic 32-byte digest" routine using the
  // browser's `subtle.digest` lazily. To keep the keyring sync,
  // we ship a pre-computed dev public key as a literal constant
  // below — derived OFFLINE by the same seed. This way:
  //   - clients verify with the literal, no async work.
  //   - the dev minter (Node) recomputes the secret key from the
  //     same seed via `@noble/hashes/sha2`.
  //
  // The literal below was generated by running:
  //   echo -n 'vector-dev-license-seed-2026' | shasum -a 256
  //   → use first 32 bytes as ed25519 secret seed
  //   → noble.getPublicKey(secret)
  // …producing the public key bytes embedded in
  // `DEV_PUBLIC_KEY_BYTES`. We keep the function around to
  // document the derivation contract.
  throw new Error(
    'deriveDevSecretKey is not callable in client code; the dev minter derives it server-side',
  );
};
// Reference the helper so TypeScript / lint don't flag it as
// unused — it exists as living documentation of the derivation.
void deriveDevSecretKey;

/** Pre-computed dev public key (32 bytes raw Ed25519). Generated
 *  by `scripts/dev-mint-license.mjs --print-pub` from the seed
 *  `vector-dev-license-seed-2026`. Bumping the seed bumps this
 *  array. */
const DEV_PUBLIC_KEY_BYTES = new Uint8Array([
  29, 8, 163, 44, 171, 55, 240, 132, 235, 108, 122, 49, 22, 248, 153, 25, 64, 208, 87, 215, 4, 83,
  200, 50, 175, 19, 168, 169, 232, 201, 189, 96,
]);

/** Production master public key (`vector-master-2026`). Stays
 *  null until the operator deploys the production minter and
 *  copies the matching public key here. Until then,
 *  non-production builds accept `dev-2026` tokens — production
 *  builds reject everything (forcing the operator to ship a real
 *  key before billing flips on). */
const PRODUCTION_PUBLIC_KEY_BYTES: Uint8Array | null = null;

/**
 * Phase 5.2 — production gate for the `dev-2026` kid.
 *
 * `dev-2026` is signed by a key derived from a public seed
 * (`scripts/dev-mint-license.mjs`). In dev / alpha that's fine;
 * in production it would mean **anyone can mint a paid token by
 * cloning the repo**.
 *
 * `import.meta.env.MODE` is rewritten by Vite at build time:
 *   - `production` for `npm run build` (the deployed bundle).
 *   - `development` for `npm run dev`.
 *   - `test` for vitest runs.
 *
 * In production, we drop `dev-2026` from the keyring entirely
 * so the verifier returns `unknown-kid` for any token signed by
 * the dev key. The license activation UI surfaces that as
 * "this token came from a dev / staging build, please re-purchase
 * via the production server".
 */
const isProductionBuild = ((): boolean => {
  try {
    // import.meta.env may not exist in node test contexts.
    const meta = (import.meta as unknown as { env?: { MODE?: string } }).env;
    return meta?.MODE === 'production';
  } catch {
    return false;
  }
})();

export const LICENSE_KEYRING: Readonly<Record<string, Uint8Array>> = (() => {
  const map: Record<string, Uint8Array> = {};
  if (!isProductionBuild) {
    // Dev / test / staging — the dev kid is accepted so engineers
    // can mint their own test tokens via `npm run license:mint`.
    map[DEV_KID] = DEV_PUBLIC_KEY_BYTES;
  }
  if (PRODUCTION_PUBLIC_KEY_BYTES) {
    map['vector-master-2026'] = PRODUCTION_PUBLIC_KEY_BYTES;
  }
  return map;
})();
